CREATE TABLE users (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    role VARCHAR2(50) NOT NULL
);

CREATE TABLE tickets (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(4000) NOT NULL,
    priority VARCHAR2(50) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    status VARCHAR2(50) DEFAULT 'OPEN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id NUMBER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    comment_text VARCHAR2(4000) NOT NULL,
    comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    commented_by NUMBER REFERENCES users(id) ON DELETE SET NULL,
    ticket_id NUMBER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    action VARCHAR2(50) NOT NULL,
    changed_by NUMBER,
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
);